### ISSUE TITLE
Something wrong for the code in ImageNet folder. 

### ISSUE THREAD

**Issue by lianqing11** [Boyiliee/MoEx#1]
Hi author, 

Thanks for your wonderful work and releasing your code. I have some problems for your code under the ImageNet folder.  For your MoEx component in moex_resnet.py, you calculate the mean and std and affine it with the mean and std from another example. But it seems that you have not assign the output result back to your x. 

I am not sure if it is wrong? I check the program, the value in the x do not change after going through the moex function. 
```
        if ex_index is not None and moex_layer == 'stem':
            moex(x, ex_index, moex_norm, moex_epsilon, moex_positive_only)
```

**Comment by felixgwu** [comment]
Hi @lianqing11,

Thank you so much for pointing this out. You are right, it should be
```
        if ex_index is not None and moex_layer == 'stem':
             x = moex(x, ex_index, moex_norm, moex_epsilon, moex_positive_only)
```
This has been fixed in the new commit. 

Best,
Felix

**Comment by lianqing11** [comment]
Dear @felixgwu ,

Thanks for your prompt reply. I am curious that if it would influence the conclusion in your paper?

Best regards,
Qing Lian

**Comment by Boyiliee** [comment]
Hi, @lianqing11 ,

Thanks a lot for your question. Sorry for your confusion. 

Currently, we only provide a code template for ImageNet. We will release the runnable code in a few weeks. If you want to have a try, please feel free to train/test on CIFAR/MODELNET code. 

Hope this helps.

Best,
Boyi
