### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by yifanjiang19** [Boyiliee/MoEx#2]
Hi,

Thanks for sharing your work. Could you please help provide the visualization code/tool that can generate similar figures like Fig.1 ?

**Comment by Boyiliee** [comment]
Hi, 

Thanks for your interest in MoEx!

Please refer to maplotlib to choose your colormaps: https://matplotlib.org/3.1.1/tutorials/colors/colormaps.html 

Hope this helps.

Best,
Boyi
