### ISSUE TITLE
MoEx normalization for text classification

### ISSUE THREAD

**Issue by Mahhos** [Boyiliee/MoEx#3]
Hi. Thanks for the great repo. I want to apply MoEx on text classification. I was wondering what type of normalization I should use for MoEx on a transformer-based model like RoBERTa to get the mean and std. 
<img width="316" alt="image" src="https://user-images.githubusercontent.com/8036251/177368178-bb8593c1-ec31-4e41-a183-08d77f52526c.png">

**Comment by Boyiliee** [comment]
Hi, @Mahhos,

We haven't tried this before, but I guess layer normalization might be better? Since it is one of the most standard normalization methods in NLP.

Hope this helps.

Best,
Boyi

**Comment by Mahhos** [comment]
Thanks for your response. Yes, layer normalization makes sense. With layer norm, I was wondering if the interpolation formula (injecting the moments of sample B to the normalized features of sample A) can stay the same as the one you proposed in your paper.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/8036251/178012952-a8a4cba9-180f-4e9e-93d9-7f725c0421d8.png">
